title: Lazy Squirrel Labs
tagline: Lazy Squirrel Labs
description: Lazy Squirrel Labs
baseurl: /
url: lslabs.dev
theme: jekyll-theme-cayman
homepage: /maintenance.html
repository: LazySquirrelLabs/lazysquirrellabs.github.io
